doma:
  dialect: postgres
  query-timeout: 60
  naming: snake-lower-case

spring:
  data:
    mongodb:
      database: crud-db
      host: localhost
      port: 27017
      username: crud-user
      password: crud-user