version: "3"
services:
  crud-db:
    build:
      context: ../
      dockerfile: docker/mongodb/Dockerfile
    container_name: crud-db
    environment:
      - LC_ALL=C.UTF-8
      - MONGO_INITDB_DATABASE=crud-db
    env_file:
      - common.env
    ports:
      - 27017:27017
